services:
  database:
    image: mysql:latest
    ports:
      - "5001:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dbmusic
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  laravel-apache:
    build: https://github.com/scratch-enthusiasts/laravel.git#main
    ports:
      - "5000:80"
    depends_on:
      - "database"
      
  socket-server:
    build: https://github.com/scratch-enthusiasts/socket-server.git#main
    ports:
     - "5002:3333"
    depends_on:
      - "database"
