services:

  ###################################################################
  # likely able to combine apache/laravel into single dockerfile (todo: zak)
    
  apache:
    image: php:apache
    ports:
      - "5000:80"
    volumes:
      - web-volume:/var/www
 
  laravel:
    image: https://github.com/scratch-enthusiasts/laravel.git
    volumes:
      - web-volume:/var/www
      
  ###################################################################
  
  database:
    image: mysql:latest
    ports:
      - "5001:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  ###################################################################
  # temp java version for testing
  
  socket-server:
    build: https://github.com/scratch-enthusiasts/socket_server.git
    ports:
      - "5002:3333"
      
  ###################################################################

volumes:
  - web-volume:
